### ISSUE TITLE
runTickOnDateCheckFunc undefined error

### ISSUE THREAD

**Issue by rjwvandenberg** [JJ173/HaakuBotProject#10]
members variable can be undefined
```
/src/bot_modules/node_module.js:42
			members.forEach(function(member) {
			        ^

TypeError: Cannot read property 'forEach' of undefined
    at Timeout.runTickOnDateCheckFunc [as _onTimeout] (/src/bot_modules/node_module.js:42:12)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)
```
The error occured around the time that wardate == today became true. 

https://nodejs.org/api/timers.html

setInterval(callback, delay[, args]) is called as follows:
```
clearInterval(DateCheckInterval);
DateCheckInterval = setInterval(runTickOnDateCheckFunc, DateCheckIntervalTimer);
```
whereas the callback function expects a members argument:
```
function runTickOnDateCheckFunc(members) { ... }
```
Adding members to the argument list in setInterval may be a possible fix.

A possible problem with this may be that setInterval callback is defined at the moment of calling !new. The members variable state at that time may be different from what it will be at a later date. Does discord.js keep this object up to date? 

An alternative approach would be to remove the members argument and request the members from client inside the function body of runTickOnDateCheckFunc.

A possible bug: when issueing a !new command the following is executed:
```
DateCheckReminderBool = false;
```
This variable is not used anywhere else. So new lists will not send a reminder message. I suspect this should be:
```
bDateCheckReminder = true;
```

As a temporary solution I've commented out the creation the callback timer on lines 325-327, so that the disfunctional code will not be executed.

**Comment by JJ173** [comment]
Fixed
